baseurl = "https://somecallmejosh.github.io/majestic-monolith-blog/"

[params]
  author = "Majestic Monolith"
  base = "majestic-monolith-blog"
  description = "It is vain to do with more what can be done with less. â€“ William of Occam"
  disqusShortname = "majestic-monolith"
  title = "Majestic Monolith Blog"
  languageCode = "en-us"
